= Especificações da Bola RoboCupJunior Soccer
{docdate}
:toc: left
:sectanchors:
:sectlinks:
:xrefstyle: full
:section-refsig: Rule
:sectnums:

ifdef::basebackend-html[]
++++
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
<script src="https://hypothes.is/embed.js" async></script>
++++
endif::basebackend-html[]

:icons: font
:numbered:

Este documento contém especificações para a bola passiva (Liga Vision, bola de
golfe laranja) e a bola infravermelha grande (Liga Infrared e Liga Entry Level).

[[technical-specification-for-pulsed-soccer-ball]]
== Especificação Técnica para Bola de Soccer Pulsada

[[pulsed-preamble]]
=== Preâmbulo

Atendendo à solicitação de uma bola de soccer para torneios RCJ que fosse mais robusta
a luzes interferentes, menos consumidora de energia e mecanicamente mais resistente, o
Comitê da Liga Soccer definiu as seguintes especificações técnicas com a colaboração
especial da EK Japan e da HiTechnic.

Os produtores dessas bolas devem solicitar um processo de certificação após o qual
podem exibir o rótulo de conformidade RCJ e suas bolas serem usadas em torneios RCJ.

Bolas com estas especificações podem ser detectadas usando sensores específicos, mas
também receptores comuns de controle remoto IR (TSOP1140, TSOP31140, GP1UX511QS,
etc. — detecção liga/desliga com uma possível indicação grosseira de distância).

[[pulsed-golf-2026]]
=== Mudança para bola pulsada de tamanho de bola de golfe em 2026
A partir de 2026, o Soccer Infrared passará a usar uma nova bola IR. A
principal diferença desta bola é a mudança de tamanho de 74 mm para 42 mm de diâmetro,
o mesmo tamanho da bola passiva da Liga Vision. Mais informações serão divulgadas
durante a temporada 2025 pelo Comitê. Esta bola é Open-Source, portanto qualquer pessoa
pode produzi-la a partir dos arquivos e instruções na página do GitHub:
https://github.com/robocup-junior/ir-golf-ball .

A Liga Entry Level continuará a usar a bola infravermelha grande.
footnote:[A Liga Entry Level frequentemente utiliza kits de robótica Lego, FischerTechnik,
Vex ou outros com os quais lidar com uma bola pequena é mais difícil, especialmente
para iniciantes.]

[[pulsed-specifications]]
=== Especificações

[[ir-light]]
==== Luz IR

A bola emite luz infravermelha (IR) com comprimentos de onda na faixa de 920 nm a
960 nm, pulsada a uma frequência portadora de onda quadrada de 40 kHz. A bola deve ter
LEDs ultrabrilhantes e de ângulo amplo suficientes para minimizar a irregularidade da
saída IR.

[[pulsed-diameter]]
==== Diâmetro

O diâmetro da bola deve ser de 74 mm. Uma bola bem equilibrada deve ser utilizada.

[[pulsed-drop-test]]
==== Teste de Queda

A bola deve ser capaz de resistir ao jogo normal. Como indicação de sua durabilidade,
ela deve ser capaz de sobreviver, sem danos, a uma queda livre de 1,5 metros sobre
uma mesa ou piso de madeira.

[[pulsed-modulation]]
==== Modulação

A saída de portadora de 40 kHz da bola deve ser modulada com uma forma de onda
trapezoidal (escalonada) de frequência de 1,2 kHz. Cada ciclo de 833 microssegundos
da forma de onda de modulação deve compreender 8 pulsos de portadora em intensidade
total, seguidos (por sua vez) de 4 pulsos de portadora a 1/4 da intensidade total,
quatro pulsos a 1/16 da intensidade total e quatro pulsos a 1/64 da intensidade total,
seguidos por um espaço (ou seja, intensidade zero) de cerca de 346 microssegundos.
O nível de corrente de pico nos LEDs deve estar na faixa de 45-55 mA. A intensidade
radiante deve ser superior a 20 mW/sr por LED.

[[pulsed-battery-life]]
==== Vida da Bateria

Se a bola tiver bateria recarregável integrada, quando nova e totalmente carregada deve
durar mais de 3 horas de uso contínuo antes que o brilho dos LEDs caia para 90% do
valor inicial. Se a bola usar pilhas substituíveis, um conjunto de pilhas alcalinas de
alta qualidade novas deve durar mais de 8 horas de uso contínuo antes que o brilho dos
LEDs caia para 90% do valor inicial.

[[pulsed-coloration]]
==== Coloração

A bola não deve ter marcas ou descoloração que possam ser confundidas com os gols ou
com o próprio campo.

[[official-suppliers-for-pulsed-balls]]
=== Fornecedores oficiais para bolas pulsadas

Atualmente, há uma bola aprovada pelo Comitê da Liga Soccer:

- Bola RoboCup Junior Soccer operando no MODO A (pulsada) fabricada pela EK Japan/Elekit
(https://elekit.co.jp/en/product/RCJ-05R)

Note que esta bola era anteriormente chamada RCJ-05. Embora você possa não encontrar
mais uma bola com este nome, qualquer bola IR produzida pela EK Japan/Elekit é
considerada aprovada pelo Comitê da Liga Soccer.

[appendix]
[[passive-ball-spec]]
== Especificação Técnica para Bola de Soccer Passiva

[[passive-ball-spec-preamble]]
=== Preâmbulo

Para impulsionar o estado da arte na competição de Soccer, ao mesmo tempo em que tenta
aproximar as ligas Junior e Major, o Comitê da Liga Soccer escolheu uma bola de golfe
laranja padrão como bola "passiva". Esta é a mesma escolha feita pela Small Size
League footnote:[Veja as regras SSL em https://robocup-ssl.github.io/ssl-rules/sslrules.html#_ball]
e, como essas bolas são padronizadas, devem ser baratas e fáceis de encontrar em
qualquer lugar do mundo.

[[specifications]]
=== Especificações

[[passive-diameter]]
==== Diâmetro

O diâmetro da bola deve ser de 42 mm ± 1 mm.

[[passive-drop-test]]
==== Teste de Queda

A bola deve ser capaz de resistir ao jogo normal. Como indicação de sua durabilidade,
ela deve ser capaz de sobreviver, sem danos, a uma queda livre de 1,5 metros sobre
uma mesa ou piso de madeira.

[[passive-coloration]]
==== Coloração

A bola deve ser de cor laranja. Como a definição da cor laranja em geral não é simples,
qualquer cor que um humano consideraria laranja e que seja substancialmente diferente
das outras cores usadas no campo é aceitável. Embora os organizadores do torneio possam
fornecer bolas fosco para melhorar a visão por câmera, as equipes ainda devem estar
preparadas para jogar com as bolas fornecidas pelos organizadores do torneio.

[[passive-surface]]
==== Superfície

Gravações e rótulos impressos na superfície da bola são tolerados. A bola não deve ter
acabamento de toque suave. As equipes devem estar preparadas para jogar com bolas
conforme fornecidas pelos organizadores do torneio.

[[passive-weight]]
==== Peso

O peso da bola deve ser de 46 gramas (± 1 grama).
